-- InvGuard hardening: auditoria, soft delete, categorias e indices.
-- Ejecutar despues de:
-- 1) supabase/multi_tenant.sql
-- 2) supabase/lotes_vencimientos.sql

create extension if not exists pgcrypto;
create extension if not exists pg_trgm;

create table if not exists public.audit_logs (
  id bigint generated by default as identity primary key,
  empresa_id bigint references public.empresas(id) on delete cascade,
  actor_id uuid,
  actor_email text,
  accion text not null,
  tabla text not null,
  registro_id text,
  antes jsonb,
  despues jsonb,
  created_at timestamp with time zone not null default now()
);

create index if not exists audit_logs_empresa_fecha_idx
  on public.audit_logs (empresa_id, created_at desc);

create index if not exists audit_logs_actor_idx
  on public.audit_logs (actor_id, created_at desc);

alter table public.audit_logs enable row level security;

drop policy if exists "audit_logs_select_admin" on public.audit_logs;
create policy "audit_logs_select_admin"
  on public.audit_logs for select
  to authenticated
  using (
    public.es_super_admin()
    or public.es_admin_empresa(empresa_id)
  );

create table if not exists public.categorias (
  id bigint generated by default as identity primary key,
  empresa_id bigint not null references public.empresas(id) on delete cascade,
  nombre text not null,
  activo boolean not null default true,
  created_by uuid,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now()
);

alter table public.categorias enable row level security;

drop policy if exists "categorias_select_miembro" on public.categorias;
create policy "categorias_select_miembro"
  on public.categorias for select
  to authenticated
  using (public.tiene_acceso_empresa(empresa_id));

drop policy if exists "categorias_insert_admin" on public.categorias;
create policy "categorias_insert_admin"
  on public.categorias for insert
  to authenticated
  with check (public.es_admin_empresa(empresa_id));

drop policy if exists "categorias_update_admin" on public.categorias;
create policy "categorias_update_admin"
  on public.categorias for update
  to authenticated
  using (public.es_admin_empresa(empresa_id))
  with check (public.es_admin_empresa(empresa_id));

create unique index if not exists categorias_empresa_nombre_unique
  on public.categorias (empresa_id, lower(nombre))
  where activo = true;

create index if not exists categorias_empresa_idx
  on public.categorias (empresa_id, activo, nombre);

alter table public.productos
  add column if not exists activo boolean not null default true;

alter table public.productos
  add column if not exists created_by uuid;

alter table public.productos
  add column if not exists updated_by uuid;

alter table public.productos
  add column if not exists deleted_by uuid;

alter table public.productos
  add column if not exists updated_at timestamp with time zone not null default now();

alter table public.productos
  add column if not exists deleted_at timestamp with time zone;

alter table public.movimientos
  add column if not exists created_by uuid;

alter table public.producto_lotes
  add column if not exists created_by uuid;

alter table public.producto_lotes
  add column if not exists updated_at timestamp with time zone not null default now();

with duplicated_products as (
  select
    p.id,
    p.empresa_id,
    p.codigo,
    row_number() over (
      partition by p.empresa_id, lower(p.codigo)
      order by p.id
    ) as duplicate_order
  from public.productos p
  where p.codigo is not null
    and trim(p.codigo) <> ''
    and coalesce(p.activo, true) = true
    and p.deleted_at is null
)
update public.productos p
  set codigo = concat(p.codigo, '-', duplicated_products.duplicate_order),
      updated_at = now()
from duplicated_products
where p.id = duplicated_products.id
  and duplicated_products.duplicate_order > 1;

create unique index if not exists productos_empresa_codigo_active_unique
  on public.productos (empresa_id, lower(codigo))
  where codigo is not null
    and trim(codigo) <> ''
    and deleted_at is null
    and activo = true;

create index if not exists productos_empresa_activo_nombre_idx
  on public.productos (empresa_id, activo, nombre)
  where deleted_at is null;

create index if not exists productos_empresa_categoria_idx
  on public.productos (empresa_id, categoria)
  where deleted_at is null;

create index if not exists productos_nombre_trgm_idx
  on public.productos using gin (lower(nombre) gin_trgm_ops);

create index if not exists movimientos_empresa_producto_fecha_idx
  on public.movimientos (empresa_id, producto_id, created_at desc);

create index if not exists producto_lotes_empresa_producto_vencimiento_idx
  on public.producto_lotes (empresa_id, producto_id, fecha_vencimiento)
  where cantidad_actual > 0;

create or replace function public.es_gestor_inventario(p_empresa_id bigint)
returns boolean
language sql
security definer
set search_path = public
as $$
  select public.es_super_admin()
    or exists (
      select 1
      from public.empresa_usuarios eu
      join public.empresas e on e.id = eu.empresa_id
      where eu.empresa_id = p_empresa_id
        and eu.user_id = auth.uid()
        and eu.rol in ('ADMIN', 'SUPERVISOR')
        and e.estado in ('BETA', 'ACTIVO')
    );
$$;

drop policy if exists "productos_insert_miembro" on public.productos;
drop policy if exists "productos_insert_gestor" on public.productos;
create policy "productos_insert_gestor"
  on public.productos for insert
  to authenticated
  with check (public.es_gestor_inventario(empresa_id));

drop policy if exists "productos_update_miembro" on public.productos;
drop policy if exists "productos_update_gestor" on public.productos;
create policy "productos_update_gestor"
  on public.productos for update
  to authenticated
  using (public.es_gestor_inventario(empresa_id))
  with check (public.es_gestor_inventario(empresa_id));

drop policy if exists "producto_lotes_insert_miembro" on public.producto_lotes;
drop policy if exists "producto_lotes_insert_gestor" on public.producto_lotes;
create policy "producto_lotes_insert_gestor"
  on public.producto_lotes for insert
  to authenticated
  with check (public.es_gestor_inventario(empresa_id));

drop policy if exists "producto_lotes_update_miembro" on public.producto_lotes;
drop policy if exists "producto_lotes_update_gestor" on public.producto_lotes;
create policy "producto_lotes_update_gestor"
  on public.producto_lotes for update
  to authenticated
  using (public.es_gestor_inventario(empresa_id))
  with check (public.es_gestor_inventario(empresa_id));

create or replace function public.set_updated_at()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists productos_set_updated_at on public.productos;
create trigger productos_set_updated_at
  before update on public.productos
  for each row execute function public.set_updated_at();

drop trigger if exists producto_lotes_set_updated_at on public.producto_lotes;
create trigger producto_lotes_set_updated_at
  before update on public.producto_lotes
  for each row execute function public.set_updated_at();

drop trigger if exists categorias_set_updated_at on public.categorias;
create trigger categorias_set_updated_at
  before update on public.categorias
  for each row execute function public.set_updated_at();

create or replace function public.audit_row_change()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_empresa_id bigint;
  v_record_id text;
  v_actor_email text;
begin
  if tg_op = 'DELETE' then
    v_empresa_id := (to_jsonb(old) ->> 'empresa_id')::bigint;
    v_record_id := to_jsonb(old) ->> 'id';
  else
    v_empresa_id := (to_jsonb(new) ->> 'empresa_id')::bigint;
    v_record_id := to_jsonb(new) ->> 'id';
  end if;

  select au.email::text
    into v_actor_email
  from auth.users au
  where au.id = auth.uid();

  insert into public.audit_logs (
    empresa_id,
    actor_id,
    actor_email,
    accion,
    tabla,
    registro_id,
    antes,
    despues
  )
  values (
    v_empresa_id,
    auth.uid(),
    v_actor_email,
    tg_op,
    tg_table_name,
    v_record_id,
    case when tg_op in ('UPDATE', 'DELETE') then to_jsonb(old) else null end,
    case when tg_op in ('INSERT', 'UPDATE') then to_jsonb(new) else null end
  );

  return coalesce(new, old);
end;
$$;

drop trigger if exists productos_audit on public.productos;
create trigger productos_audit
  after insert or update or delete on public.productos
  for each row execute function public.audit_row_change();

drop trigger if exists movimientos_audit on public.movimientos;
create trigger movimientos_audit
  after insert or update or delete on public.movimientos
  for each row execute function public.audit_row_change();

drop trigger if exists producto_lotes_audit on public.producto_lotes;
create trigger producto_lotes_audit
  after insert or update or delete on public.producto_lotes
  for each row execute function public.audit_row_change();

drop trigger if exists categorias_audit on public.categorias;
create trigger categorias_audit
  after insert or update or delete on public.categorias
  for each row execute function public.audit_row_change();

drop trigger if exists empresa_usuarios_audit on public.empresa_usuarios;
create trigger empresa_usuarios_audit
  after insert or update or delete on public.empresa_usuarios
  for each row execute function public.audit_row_change();

create or replace function public.soft_delete_producto(
  p_empresa_id bigint,
  p_producto_id bigint
)
returns table (
  id bigint,
  deleted_at timestamp with time zone
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_producto public.productos;
begin
  if not public.es_admin_empresa(p_empresa_id) then
    raise exception 'Solo un ADMIN puede eliminar productos';
  end if;

  update public.productos p
    set activo = false,
        deleted_at = now(),
        deleted_by = auth.uid(),
        updated_by = auth.uid()
  where p.id = p_producto_id
    and p.empresa_id = p_empresa_id
    and p.deleted_at is null
  returning * into v_producto;

  if v_producto.id is null then
    raise exception 'Producto no encontrado o ya eliminado';
  end if;

  return query select v_producto.id, v_producto.deleted_at;
end;
$$;

create or replace function public.registrar_movimiento_lote(
  p_empresa_id bigint,
  p_producto_id bigint,
  p_tipo text,
  p_cantidad numeric,
  p_observacion text default '',
  p_fecha_vencimiento date default null,
  p_codigo_lote text default '',
  p_proveedor text default ''
)
returns table (
  movimiento_id bigint,
  stock_actual numeric
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_stock numeric;
  v_nuevo_stock numeric;
  v_movimiento_id bigint;
  v_restante numeric;
  v_consumir numeric;
  v_lote public.producto_lotes;
begin
  if not public.tiene_acceso_empresa(p_empresa_id) then
    raise exception 'No tienes acceso a esta empresa';
  end if;

  if p_cantidad <= 0 then
    raise exception 'La cantidad debe ser mayor a cero';
  end if;

  select p.stock
    into v_stock
  from public.productos p
  where p.id = p_producto_id
    and p.empresa_id = p_empresa_id
    and p.activo = true
    and p.deleted_at is null
  for update;

  if not found then
    raise exception 'Producto no encontrado o inactivo';
  end if;

  if p_tipo = 'ENTRADA' then
    v_nuevo_stock := v_stock + p_cantidad;
  elsif p_tipo = 'SALIDA' then
    v_nuevo_stock := v_stock - p_cantidad;
  else
    raise exception 'Tipo de movimiento invalido';
  end if;

  if v_nuevo_stock < 0 then
    raise exception 'Stock insuficiente';
  end if;

  update public.productos p
    set stock = v_nuevo_stock,
        updated_by = auth.uid()
  where p.id = p_producto_id
    and p.empresa_id = p_empresa_id;

  if p_tipo = 'ENTRADA'
    and (
      p_fecha_vencimiento is not null
      or nullif(trim(p_codigo_lote), '') is not null
      or nullif(trim(p_proveedor), '') is not null
    ) then
    insert into public.producto_lotes (
      empresa_id,
      producto_id,
      codigo_lote,
      proveedor,
      fecha_ingreso,
      fecha_vencimiento,
      cantidad_inicial,
      cantidad_actual,
      created_by
    )
    values (
      p_empresa_id,
      p_producto_id,
      nullif(trim(p_codigo_lote), ''),
      nullif(trim(p_proveedor), ''),
      current_date,
      p_fecha_vencimiento,
      p_cantidad,
      p_cantidad,
      auth.uid()
    );
  end if;

  if p_tipo = 'SALIDA' then
    v_restante := p_cantidad;

    for v_lote in
      select pl.*
      from public.producto_lotes pl
      where pl.empresa_id = p_empresa_id
        and pl.producto_id = p_producto_id
        and pl.cantidad_actual > 0
      order by pl.fecha_vencimiento asc nulls last, pl.created_at asc
      for update
    loop
      exit when v_restante <= 0;

      v_consumir := least(v_restante, v_lote.cantidad_actual);

      update public.producto_lotes pl
        set cantidad_actual = pl.cantidad_actual - v_consumir
      where pl.id = v_lote.id;

      v_restante := v_restante - v_consumir;
    end loop;
  end if;

  insert into public.movimientos (
    empresa_id,
    producto_id,
    tipo,
    cantidad,
    observacion,
    created_by
  )
  values (
    p_empresa_id,
    p_producto_id,
    p_tipo,
    p_cantidad,
    nullif(trim(p_observacion), ''),
    auth.uid()
  )
  returning id into v_movimiento_id;

  return query select v_movimiento_id, v_nuevo_stock;
end;
$$;

grant select on public.audit_logs to authenticated;
grant select, insert, update on public.categorias to authenticated;
grant usage, select on sequence public.categorias_id_seq to authenticated;
grant execute on function public.soft_delete_producto(bigint, bigint) to authenticated;
grant execute on function public.registrar_movimiento_lote(
  bigint,
  bigint,
  text,
  numeric,
  text,
  date,
  text,
  text
) to authenticated;
