-- InvGuard: lotes, vencimientos, FEFO y perdidas sugeridas.
-- Ejecutar en Supabase SQL Editor.

create table if not exists public.producto_lotes (
  id bigint generated by default as identity primary key,
  empresa_id bigint not null references public.empresas(id) on delete cascade,
  producto_id bigint not null references public.productos(id) on delete cascade,
  codigo_lote text,
  proveedor text,
  fecha_ingreso date not null default current_date,
  fecha_vencimiento date,
  cantidad_inicial numeric not null default 0 check (cantidad_inicial >= 0),
  cantidad_actual numeric not null default 0 check (cantidad_actual >= 0),
  created_at timestamp with time zone not null default now()
);

alter table public.producto_lotes
  add column if not exists codigo_lote text;

alter table public.producto_lotes
  add column if not exists proveedor text;

alter table public.producto_lotes
  add column if not exists fecha_ingreso date not null default current_date;

alter table public.producto_lotes
  add column if not exists fecha_vencimiento date;

alter table public.producto_lotes
  add column if not exists cantidad_inicial numeric not null default 0 check (cantidad_inicial >= 0);

alter table public.producto_lotes
  add column if not exists cantidad_actual numeric not null default 0 check (cantidad_actual >= 0);

create index if not exists producto_lotes_empresa_idx
  on public.producto_lotes (empresa_id);

create index if not exists producto_lotes_producto_idx
  on public.producto_lotes (producto_id);

create index if not exists producto_lotes_vencimiento_idx
  on public.producto_lotes (empresa_id, fecha_vencimiento);

alter table public.producto_lotes enable row level security;

drop policy if exists "producto_lotes_select_miembro" on public.producto_lotes;
create policy "producto_lotes_select_miembro"
  on public.producto_lotes for select
  to authenticated
  using (public.tiene_acceso_empresa(empresa_id));

drop policy if exists "producto_lotes_insert_miembro" on public.producto_lotes;
create policy "producto_lotes_insert_miembro"
  on public.producto_lotes for insert
  to authenticated
  with check (public.tiene_acceso_empresa(empresa_id));

drop policy if exists "producto_lotes_update_miembro" on public.producto_lotes;
create policy "producto_lotes_update_miembro"
  on public.producto_lotes for update
  to authenticated
  using (public.tiene_acceso_empresa(empresa_id))
  with check (public.tiene_acceso_empresa(empresa_id));

drop policy if exists "producto_lotes_delete_admin" on public.producto_lotes;
create policy "producto_lotes_delete_admin"
  on public.producto_lotes for delete
  to authenticated
  using (public.es_admin_empresa(empresa_id));

create or replace function public.registrar_movimiento_lote(
  p_empresa_id bigint,
  p_producto_id bigint,
  p_tipo text,
  p_cantidad numeric,
  p_observacion text default '',
  p_fecha_vencimiento date default null,
  p_codigo_lote text default '',
  p_proveedor text default ''
)
returns table (
  movimiento_id bigint,
  stock_actual numeric
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_stock numeric;
  v_nuevo_stock numeric;
  v_movimiento_id bigint;
  v_restante numeric;
  v_consumir numeric;
  v_lote public.producto_lotes;
begin
  if not public.tiene_acceso_empresa(p_empresa_id) then
    raise exception 'No tienes acceso a esta empresa';
  end if;

  if p_cantidad <= 0 then
    raise exception 'La cantidad debe ser mayor a cero';
  end if;

  select p.stock
    into v_stock
  from public.productos p
  where p.id = p_producto_id
    and p.empresa_id = p_empresa_id
  for update;

  if not found then
    raise exception 'Producto no encontrado';
  end if;

  if p_tipo = 'ENTRADA' then
    v_nuevo_stock := v_stock + p_cantidad;
  elsif p_tipo = 'SALIDA' then
    v_nuevo_stock := v_stock - p_cantidad;
  else
    raise exception 'Tipo de movimiento invalido';
  end if;

  if v_nuevo_stock < 0 then
    raise exception 'Stock insuficiente';
  end if;

  update public.productos p
    set stock = v_nuevo_stock
  where p.id = p_producto_id
    and p.empresa_id = p_empresa_id;

  if p_tipo = 'ENTRADA'
    and (
      p_fecha_vencimiento is not null
      or nullif(trim(p_codigo_lote), '') is not null
      or nullif(trim(p_proveedor), '') is not null
    ) then
    insert into public.producto_lotes (
      empresa_id,
      producto_id,
      codigo_lote,
      proveedor,
      fecha_ingreso,
      fecha_vencimiento,
      cantidad_inicial,
      cantidad_actual
    )
    values (
      p_empresa_id,
      p_producto_id,
      nullif(trim(p_codigo_lote), ''),
      nullif(trim(p_proveedor), ''),
      current_date,
      p_fecha_vencimiento,
      p_cantidad,
      p_cantidad
    );
  end if;

  if p_tipo = 'SALIDA' then
    v_restante := p_cantidad;

    for v_lote in
      select pl.*
      from public.producto_lotes pl
      where pl.empresa_id = p_empresa_id
        and pl.producto_id = p_producto_id
        and pl.cantidad_actual > 0
      order by pl.fecha_vencimiento asc nulls last, pl.created_at asc
      for update
    loop
      exit when v_restante <= 0;

      v_consumir := least(v_restante, v_lote.cantidad_actual);

      update public.producto_lotes pl
        set cantidad_actual = pl.cantidad_actual - v_consumir
      where pl.id = v_lote.id;

      v_restante := v_restante - v_consumir;
    end loop;
  end if;

  insert into public.movimientos (
    empresa_id,
    producto_id,
    tipo,
    cantidad,
    observacion
  )
  values (
    p_empresa_id,
    p_producto_id,
    p_tipo,
    p_cantidad,
    nullif(trim(p_observacion), '')
  )
  returning id into v_movimiento_id;

  return query select v_movimiento_id, v_nuevo_stock;
end;
$$;

create or replace function public.registrar_perdida_lote(
  p_empresa_id bigint,
  p_lote_id bigint,
  p_cantidad numeric default null,
  p_observacion text default ''
)
returns table (
  movimiento_id bigint,
  stock_actual numeric,
  lote_actual numeric
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_lote public.producto_lotes;
  v_producto public.productos;
  v_cantidad numeric;
  v_stock_actual numeric;
  v_lote_actual numeric;
  v_movimiento_id bigint;
  v_observacion text;
begin
  if not public.tiene_acceso_empresa(p_empresa_id) then
    raise exception 'No tienes acceso a esta empresa';
  end if;

  select pl.*
    into v_lote
  from public.producto_lotes pl
  where pl.id = p_lote_id
    and pl.empresa_id = p_empresa_id
  for update;

  if v_lote.id is null then
    raise exception 'Lote no encontrado';
  end if;

  select p.*
    into v_producto
  from public.productos p
  where p.id = v_lote.producto_id
    and p.empresa_id = p_empresa_id
  for update;

  if v_producto.id is null then
    raise exception 'Producto no encontrado';
  end if;

  v_cantidad := coalesce(p_cantidad, v_lote.cantidad_actual);

  if v_cantidad <= 0 then
    raise exception 'La cantidad debe ser mayor a cero';
  end if;

  if v_cantidad > v_lote.cantidad_actual then
    raise exception 'La cantidad supera el saldo del lote';
  end if;

  if v_cantidad > v_producto.stock then
    raise exception 'La cantidad supera el stock actual del producto';
  end if;

  v_stock_actual := v_producto.stock - v_cantidad;
  v_lote_actual := v_lote.cantidad_actual - v_cantidad;
  v_observacion := concat_ws(
    ' - ',
    'PERDIDA: Vencimiento',
    nullif(trim(p_observacion), ''),
    case
      when v_lote.codigo_lote is not null then 'Lote ' || v_lote.codigo_lote
      else null
    end,
    case
      when v_lote.fecha_vencimiento is not null then 'Vence ' || v_lote.fecha_vencimiento::text
      else null
    end
  );

  update public.productos p
    set stock = v_stock_actual
  where p.id = v_producto.id
    and p.empresa_id = p_empresa_id;

  update public.producto_lotes pl
    set cantidad_actual = v_lote_actual
  where pl.id = v_lote.id;

  insert into public.movimientos (
    empresa_id,
    producto_id,
    tipo,
    cantidad,
    observacion
  )
  values (
    p_empresa_id,
    v_producto.id,
    'SALIDA',
    v_cantidad,
    v_observacion
  )
  returning id into v_movimiento_id;

  return query select v_movimiento_id, v_stock_actual, v_lote_actual;
end;
$$;

grant select, insert, update, delete on public.producto_lotes to authenticated;
grant usage, select on sequence public.producto_lotes_id_seq to authenticated;

grant execute on function public.registrar_movimiento_lote(
  bigint,
  bigint,
  text,
  numeric,
  text,
  date,
  text,
  text
) to authenticated;

grant execute on function public.registrar_perdida_lote(
  bigint,
  bigint,
  numeric,
  text
) to authenticated;
