-- InvGuard: proveedores, cuentas por pagar y abonos.
-- Ejecutar despues de supabase/hardening.sql.

create table if not exists public.proveedores (
  id bigint generated by default as identity primary key,
  empresa_id bigint not null references public.empresas(id) on delete cascade,
  nombre text not null,
  documento text,
  contacto text,
  telefono text,
  email text,
  notas text,
  activo boolean not null default true,
  created_by uuid,
  updated_by uuid,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now()
);

create table if not exists public.cuentas_por_pagar (
  id bigint generated by default as identity primary key,
  empresa_id bigint not null references public.empresas(id) on delete cascade,
  proveedor_id bigint not null references public.proveedores(id) on delete restrict,
  concepto text not null,
  documento_ref text,
  fecha_emision date not null default current_date,
  fecha_vencimiento date not null check (fecha_vencimiento >= fecha_emision),
  total numeric(14, 2) not null check (total > 0),
  saldo numeric(14, 2) not null check (saldo >= 0 and saldo <= total),
  estado text not null default 'PENDIENTE'
    check (estado in ('PENDIENTE', 'PARCIAL', 'PAGADO', 'ANULADO')),
  recordatorio_dias integer not null default 3 check (recordatorio_dias between 0 and 90),
  notas text,
  created_by uuid,
  updated_by uuid,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now()
);

create table if not exists public.pagos_proveedor (
  id bigint generated by default as identity primary key,
  empresa_id bigint not null references public.empresas(id) on delete cascade,
  cuenta_id bigint not null references public.cuentas_por_pagar(id) on delete restrict,
  monto numeric(14, 2) not null check (monto > 0),
  fecha_pago date not null default current_date,
  medio text not null default 'TRANSFERENCIA'
    check (medio in ('EFECTIVO', 'TRANSFERENCIA', 'TARJETA', 'CHEQUE', 'OTRO')),
  referencia text,
  notas text,
  created_by uuid,
  created_at timestamp with time zone not null default now()
);

create unique index if not exists proveedores_empresa_nombre_unique
  on public.proveedores (empresa_id, lower(nombre))
  where activo = true;

create index if not exists proveedores_empresa_activo_idx
  on public.proveedores (empresa_id, activo, nombre);

create index if not exists cuentas_pagar_empresa_estado_vencimiento_idx
  on public.cuentas_por_pagar (empresa_id, estado, fecha_vencimiento);

create index if not exists cuentas_pagar_proveedor_idx
  on public.cuentas_por_pagar (proveedor_id, fecha_vencimiento desc);

create index if not exists pagos_proveedor_cuenta_fecha_idx
  on public.pagos_proveedor (cuenta_id, fecha_pago desc);

alter table public.proveedores enable row level security;
alter table public.cuentas_por_pagar enable row level security;
alter table public.pagos_proveedor enable row level security;

drop policy if exists "proveedores_select_miembro" on public.proveedores;
create policy "proveedores_select_miembro"
  on public.proveedores for select
  to authenticated
  using (public.tiene_acceso_empresa(empresa_id));

drop policy if exists "proveedores_insert_gestor" on public.proveedores;
create policy "proveedores_insert_gestor"
  on public.proveedores for insert
  to authenticated
  with check (public.es_gestor_inventario(empresa_id));

drop policy if exists "proveedores_update_gestor" on public.proveedores;
create policy "proveedores_update_gestor"
  on public.proveedores for update
  to authenticated
  using (public.es_gestor_inventario(empresa_id))
  with check (public.es_gestor_inventario(empresa_id));

drop policy if exists "cuentas_pagar_select_miembro" on public.cuentas_por_pagar;
create policy "cuentas_pagar_select_miembro"
  on public.cuentas_por_pagar for select
  to authenticated
  using (public.tiene_acceso_empresa(empresa_id));

drop policy if exists "cuentas_pagar_insert_gestor" on public.cuentas_por_pagar;
create policy "cuentas_pagar_insert_gestor"
  on public.cuentas_por_pagar for insert
  to authenticated
  with check (public.es_gestor_inventario(empresa_id));

drop policy if exists "pagos_proveedor_select_miembro" on public.pagos_proveedor;
create policy "pagos_proveedor_select_miembro"
  on public.pagos_proveedor for select
  to authenticated
  using (public.tiene_acceso_empresa(empresa_id));

create or replace function public.preparar_cuenta_por_pagar()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if not exists (
    select 1
    from public.proveedores p
    where p.id = new.proveedor_id
      and p.empresa_id = new.empresa_id
      and p.activo = true
  ) then
    raise exception 'Proveedor no encontrado o inactivo';
  end if;

  new.saldo = new.total;
  new.estado = 'PENDIENTE';
  new.created_by = coalesce(new.created_by, auth.uid());
  new.updated_by = auth.uid();
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists cuentas_pagar_prepare_insert on public.cuentas_por_pagar;
create trigger cuentas_pagar_prepare_insert
  before insert on public.cuentas_por_pagar
  for each row execute function public.preparar_cuenta_por_pagar();

drop trigger if exists proveedores_set_updated_at on public.proveedores;
create trigger proveedores_set_updated_at
  before update on public.proveedores
  for each row execute function public.set_updated_at();

drop trigger if exists cuentas_pagar_set_updated_at on public.cuentas_por_pagar;
create trigger cuentas_pagar_set_updated_at
  before update on public.cuentas_por_pagar
  for each row execute function public.set_updated_at();

drop trigger if exists proveedores_audit on public.proveedores;
create trigger proveedores_audit
  after insert or update or delete on public.proveedores
  for each row execute function public.audit_row_change();

drop trigger if exists cuentas_pagar_audit on public.cuentas_por_pagar;
create trigger cuentas_pagar_audit
  after insert or update or delete on public.cuentas_por_pagar
  for each row execute function public.audit_row_change();

drop trigger if exists pagos_proveedor_audit on public.pagos_proveedor;
create trigger pagos_proveedor_audit
  after insert or update or delete on public.pagos_proveedor
  for each row execute function public.audit_row_change();

create or replace function public.registrar_pago_proveedor(
  p_empresa_id bigint,
  p_cuenta_id bigint,
  p_monto numeric,
  p_fecha_pago date default current_date,
  p_medio text default 'TRANSFERENCIA',
  p_referencia text default '',
  p_notas text default ''
)
returns table (
  pago_id bigint,
  saldo_actual numeric,
  estado_actual text
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_cuenta public.cuentas_por_pagar;
  v_pago_id bigint;
  v_saldo numeric;
  v_estado text;
  v_medio text := upper(trim(p_medio));
begin
  if not public.es_gestor_inventario(p_empresa_id) then
    raise exception 'No tienes permiso para registrar pagos';
  end if;

  if p_monto is null or p_monto <= 0 then
    raise exception 'El monto debe ser mayor a cero';
  end if;

  if p_fecha_pago > current_date then
    raise exception 'La fecha del pago no puede estar en el futuro';
  end if;

  if v_medio not in ('EFECTIVO', 'TRANSFERENCIA', 'TARJETA', 'CHEQUE', 'OTRO') then
    raise exception 'Medio de pago invalido';
  end if;

  select cpp.*
    into v_cuenta
  from public.cuentas_por_pagar cpp
  where cpp.id = p_cuenta_id
    and cpp.empresa_id = p_empresa_id
  for update;

  if v_cuenta.id is null then
    raise exception 'Cuenta por pagar no encontrada';
  end if;

  if v_cuenta.estado in ('PAGADO', 'ANULADO') then
    raise exception 'Esta cuenta ya no acepta pagos';
  end if;

  if p_monto > v_cuenta.saldo then
    raise exception 'El pago supera el saldo pendiente';
  end if;

  v_saldo := v_cuenta.saldo - p_monto;
  v_estado := case when v_saldo = 0 then 'PAGADO' else 'PARCIAL' end;

  insert into public.pagos_proveedor (
    empresa_id,
    cuenta_id,
    monto,
    fecha_pago,
    medio,
    referencia,
    notas,
    created_by
  )
  values (
    p_empresa_id,
    p_cuenta_id,
    p_monto,
    coalesce(p_fecha_pago, current_date),
    v_medio,
    nullif(trim(p_referencia), ''),
    nullif(trim(p_notas), ''),
    auth.uid()
  )
  returning id into v_pago_id;

  update public.cuentas_por_pagar cpp
    set saldo = v_saldo,
        estado = v_estado,
        updated_by = auth.uid()
  where cpp.id = v_cuenta.id;

  return query select v_pago_id, v_saldo, v_estado;
end;
$$;

grant select, insert, update on public.proveedores to authenticated;
grant select, insert on public.cuentas_por_pagar to authenticated;
grant select on public.pagos_proveedor to authenticated;
grant usage, select on sequence public.proveedores_id_seq to authenticated;
grant usage, select on sequence public.cuentas_por_pagar_id_seq to authenticated;
grant usage, select on sequence public.pagos_proveedor_id_seq to authenticated;
grant execute on function public.registrar_pago_proveedor(
  bigint,
  bigint,
  numeric,
  date,
  text,
  text,
  text
) to authenticated;
