-- InvGuard multi-tenant SaaS schema
-- Ejecutar en Supabase SQL Editor.
-- Este script separa los datos por empresa y usuario con RLS.

create extension if not exists pgcrypto;

create table if not exists public.empresas (
  id bigint generated by default as identity primary key,
  owner_id uuid references auth.users(id) on delete cascade,
  nombre text not null,
  rubro text,
  ciudad text,
  estado text not null default 'ACTIVA',
  created_at timestamp with time zone not null default now()
);

alter table public.empresas
  add column if not exists owner_id uuid references auth.users(id) on delete cascade;

alter table public.empresas
  add column if not exists rubro text;

alter table public.empresas
  add column if not exists ciudad text;

alter table public.empresas
  add column if not exists estado text not null default 'ACTIVA';

alter table public.empresas
  add column if not exists created_at timestamp with time zone not null default now();

create table if not exists public.empresa_usuarios (
  id bigint generated by default as identity primary key,
  empresa_id bigint not null references public.empresas(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  email text,
  rol text not null default 'ADMIN' check (rol in ('ADMIN', 'SUPERVISOR', 'EMPLEADO')),
  created_at timestamp with time zone not null default now(),
  unique (empresa_id, user_id)
);

alter table public.empresa_usuarios
  add column if not exists email text;

create table if not exists public.invitaciones_empresa (
  id uuid primary key default gen_random_uuid(),
  empresa_id bigint not null references public.empresas(id) on delete cascade,
  email text not null,
  rol text not null default 'EMPLEADO' check (rol in ('ADMIN', 'SUPERVISOR', 'EMPLEADO')),
  token text not null unique default encode(gen_random_bytes(18), 'hex'),
  estado text not null default 'PENDIENTE' check (estado in ('PENDIENTE', 'ACEPTADA', 'CANCELADA')),
  created_by uuid not null references auth.users(id) on delete cascade,
  accepted_by uuid references auth.users(id) on delete set null,
  expires_at timestamp with time zone not null default (now() + interval '7 days'),
  created_at timestamp with time zone not null default now()
);

create table if not exists public.productos (
  id bigint generated by default as identity primary key,
  empresa_id bigint not null references public.empresas(id) on delete cascade,
  codigo text,
  nombre text not null,
  categoria text,
  stock numeric not null default 0 check (stock >= 0),
  stock_minimo numeric not null default 0 check (stock_minimo >= 0),
  precio_compra numeric not null default 0 check (precio_compra >= 0),
  precio_venta numeric not null default 0 check (precio_venta >= 0),
  created_at timestamp with time zone not null default now()
);

alter table public.productos
  add column if not exists empresa_id bigint references public.empresas(id) on delete cascade;

alter table public.productos
  add column if not exists codigo text;

alter table public.productos
  add column if not exists categoria text;

alter table public.productos
  add column if not exists stock numeric not null default 0 check (stock >= 0);

alter table public.productos
  add column if not exists stock_minimo numeric not null default 0 check (stock_minimo >= 0);

alter table public.productos
  add column if not exists precio_compra numeric not null default 0 check (precio_compra >= 0);

alter table public.productos
  add column if not exists precio_venta numeric not null default 0 check (precio_venta >= 0);

create table if not exists public.movimientos (
  id bigint generated by default as identity primary key,
  empresa_id bigint not null references public.empresas(id) on delete cascade,
  producto_id bigint not null references public.productos(id) on delete restrict,
  tipo text not null check (tipo in ('ENTRADA', 'SALIDA')),
  cantidad numeric not null check (cantidad > 0),
  observacion text,
  created_at timestamp with time zone not null default now()
);

alter table public.movimientos
  add column if not exists empresa_id bigint references public.empresas(id) on delete cascade;

alter table public.movimientos
  add column if not exists producto_id bigint references public.productos(id) on delete restrict;

alter table public.movimientos
  add column if not exists tipo text check (tipo in ('ENTRADA', 'SALIDA'));

alter table public.movimientos
  add column if not exists cantidad numeric check (cantidad > 0);

alter table public.movimientos
  add column if not exists observacion text;

alter table public.movimientos
  add column if not exists created_at timestamp with time zone not null default now();

create index if not exists empresas_owner_idx
  on public.empresas (owner_id);

create index if not exists empresa_usuarios_user_idx
  on public.empresa_usuarios (user_id);

create index if not exists empresa_usuarios_empresa_idx
  on public.empresa_usuarios (empresa_id);

create index if not exists invitaciones_empresa_idx
  on public.invitaciones_empresa (empresa_id, estado);

create index if not exists invitaciones_token_idx
  on public.invitaciones_empresa (token);

create index if not exists productos_empresa_idx
  on public.productos (empresa_id);

create index if not exists movimientos_empresa_fecha_idx
  on public.movimientos (empresa_id, created_at desc);

create index if not exists movimientos_producto_idx
  on public.movimientos (producto_id);

create or replace function public.es_miembro_empresa(p_empresa_id bigint)
returns boolean
language sql
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.empresa_usuarios eu
    where eu.empresa_id = p_empresa_id
      and eu.user_id = auth.uid()
  );
$$;

create or replace function public.es_admin_empresa(p_empresa_id bigint)
returns boolean
language sql
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.empresa_usuarios eu
    where eu.empresa_id = p_empresa_id
      and eu.user_id = auth.uid()
      and eu.rol = 'ADMIN'
  );
$$;

alter table public.empresas enable row level security;
alter table public.empresa_usuarios enable row level security;
alter table public.invitaciones_empresa enable row level security;
alter table public.productos enable row level security;
alter table public.movimientos enable row level security;

drop policy if exists "empresas_select_miembro" on public.empresas;
create policy "empresas_select_miembro"
  on public.empresas for select
  to authenticated
  using (
    owner_id = auth.uid()
    or public.es_miembro_empresa(id)
  );

drop policy if exists "empresas_insert_owner" on public.empresas;
create policy "empresas_insert_owner"
  on public.empresas for insert
  to authenticated
  with check (owner_id = auth.uid());

drop policy if exists "empresas_update_admin" on public.empresas;
create policy "empresas_update_admin"
  on public.empresas for update
  to authenticated
  using (public.es_admin_empresa(id) or owner_id = auth.uid())
  with check (public.es_admin_empresa(id) or owner_id = auth.uid());

drop policy if exists "empresa_usuarios_select_miembro" on public.empresa_usuarios;
create policy "empresa_usuarios_select_miembro"
  on public.empresa_usuarios for select
  to authenticated
  using (
    user_id = auth.uid()
    or public.es_miembro_empresa(empresa_id)
  );

drop policy if exists "empresa_usuarios_insert_self_or_admin" on public.empresa_usuarios;
create policy "empresa_usuarios_insert_self_or_admin"
  on public.empresa_usuarios for insert
  to authenticated
  with check (
    (
      user_id = auth.uid()
      and exists (
        select 1
        from public.empresas e
        where e.id = empresa_id
          and e.owner_id = auth.uid()
      )
    )
    or public.es_admin_empresa(empresa_id)
  );

drop policy if exists "empresa_usuarios_update_admin" on public.empresa_usuarios;
create policy "empresa_usuarios_update_admin"
  on public.empresa_usuarios for update
  to authenticated
  using (public.es_admin_empresa(empresa_id))
  with check (public.es_admin_empresa(empresa_id));

drop policy if exists "empresa_usuarios_delete_admin" on public.empresa_usuarios;
create policy "empresa_usuarios_delete_admin"
  on public.empresa_usuarios for delete
  to authenticated
  using (public.es_admin_empresa(empresa_id));

drop policy if exists "invitaciones_select_admin" on public.invitaciones_empresa;
create policy "invitaciones_select_admin"
  on public.invitaciones_empresa for select
  to authenticated
  using (
    public.es_admin_empresa(empresa_id)
    or lower(email) = lower(coalesce(auth.jwt() ->> 'email', ''))
  );

drop policy if exists "invitaciones_insert_admin" on public.invitaciones_empresa;
create policy "invitaciones_insert_admin"
  on public.invitaciones_empresa for insert
  to authenticated
  with check (
    public.es_admin_empresa(empresa_id)
    and created_by = auth.uid()
  );

drop policy if exists "invitaciones_update_admin" on public.invitaciones_empresa;
create policy "invitaciones_update_admin"
  on public.invitaciones_empresa for update
  to authenticated
  using (
    public.es_admin_empresa(empresa_id)
    or lower(email) = lower(coalesce(auth.jwt() ->> 'email', ''))
  )
  with check (
    public.es_admin_empresa(empresa_id)
    or lower(email) = lower(coalesce(auth.jwt() ->> 'email', ''))
  );

drop policy if exists "productos_select_miembro" on public.productos;
create policy "productos_select_miembro"
  on public.productos for select
  to authenticated
  using (public.es_miembro_empresa(empresa_id));

drop policy if exists "productos_insert_miembro" on public.productos;
create policy "productos_insert_miembro"
  on public.productos for insert
  to authenticated
  with check (public.es_miembro_empresa(empresa_id));

drop policy if exists "productos_update_miembro" on public.productos;
create policy "productos_update_miembro"
  on public.productos for update
  to authenticated
  using (public.es_miembro_empresa(empresa_id))
  with check (public.es_miembro_empresa(empresa_id));

drop policy if exists "productos_delete_admin" on public.productos;
create policy "productos_delete_admin"
  on public.productos for delete
  to authenticated
  using (public.es_admin_empresa(empresa_id));

drop policy if exists "movimientos_select_miembro" on public.movimientos;
create policy "movimientos_select_miembro"
  on public.movimientos for select
  to authenticated
  using (public.es_miembro_empresa(empresa_id));

drop policy if exists "movimientos_insert_miembro" on public.movimientos;
create policy "movimientos_insert_miembro"
  on public.movimientos for insert
  to authenticated
  with check (public.es_miembro_empresa(empresa_id));

drop policy if exists "movimientos_update_admin" on public.movimientos;
create policy "movimientos_update_admin"
  on public.movimientos for update
  to authenticated
  using (public.es_admin_empresa(empresa_id))
  with check (public.es_admin_empresa(empresa_id));

drop policy if exists "movimientos_delete_admin" on public.movimientos;
create policy "movimientos_delete_admin"
  on public.movimientos for delete
  to authenticated
  using (public.es_admin_empresa(empresa_id));

create or replace function public.registrar_movimiento(
  p_empresa_id bigint,
  p_producto_id bigint,
  p_tipo text,
  p_cantidad numeric,
  p_observacion text default ''
)
returns table (
  movimiento_id bigint,
  stock_actual numeric
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_stock numeric;
  v_nuevo_stock numeric;
  v_movimiento_id bigint;
begin
  if not public.es_miembro_empresa(p_empresa_id) then
    raise exception 'No tienes acceso a esta empresa';
  end if;

  if p_cantidad <= 0 then
    raise exception 'La cantidad debe ser mayor a cero';
  end if;

  select stock
    into v_stock
  from public.productos
  where id = p_producto_id
    and empresa_id = p_empresa_id
  for update;

  if not found then
    raise exception 'Producto no encontrado';
  end if;

  if p_tipo = 'ENTRADA' then
    v_nuevo_stock := v_stock + p_cantidad;
  elsif p_tipo = 'SALIDA' then
    v_nuevo_stock := v_stock - p_cantidad;
  else
    raise exception 'Tipo de movimiento invalido';
  end if;

  if v_nuevo_stock < 0 then
    raise exception 'Stock insuficiente';
  end if;

  update public.productos
    set stock = v_nuevo_stock
  where id = p_producto_id
    and empresa_id = p_empresa_id;

  insert into public.movimientos (
    empresa_id,
    producto_id,
    tipo,
    cantidad,
    observacion
  )
  values (
    p_empresa_id,
    p_producto_id,
    p_tipo,
    p_cantidad,
    nullif(trim(p_observacion), '')
  )
  returning id into v_movimiento_id;

  return query select v_movimiento_id, v_nuevo_stock;
end;
$$;

grant execute on function public.registrar_movimiento(
  bigint,
  bigint,
  text,
  numeric,
  text
) to authenticated;

create or replace function public.crear_invitacion_empresa(
  p_empresa_id bigint,
  p_email text,
  p_rol text default 'EMPLEADO'
)
returns table (
  id uuid,
  token text,
  email text,
  rol text,
  expires_at timestamp with time zone
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_invite public.invitaciones_empresa;
begin
  if not public.es_admin_empresa(p_empresa_id) then
    raise exception 'Solo un ADMIN puede invitar usuarios';
  end if;

  if p_rol not in ('ADMIN', 'SUPERVISOR', 'EMPLEADO') then
    raise exception 'Rol invalido';
  end if;

  insert into public.invitaciones_empresa (
    empresa_id,
    email,
    rol,
    created_by
  )
  values (
    p_empresa_id,
    lower(trim(p_email)),
    p_rol,
    auth.uid()
  )
  returning * into v_invite;

  return query
    select
      v_invite.id,
      v_invite.token,
      v_invite.email,
      v_invite.rol,
      v_invite.expires_at;
end;
$$;

create or replace function public.aceptar_invitacion_empresa(
  p_token text
)
returns table (
  empresa_id bigint,
  rol text
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_invite public.invitaciones_empresa;
  v_user_email text;
begin
  select email
    into v_user_email
  from auth.users
  where id = auth.uid();

  if v_user_email is null then
    raise exception 'Usuario no autenticado';
  end if;

  select *
    into v_invite
  from public.invitaciones_empresa
  where token = p_token
    and estado = 'PENDIENTE'
  for update;

  if not found then
    raise exception 'Invitacion no encontrada o ya usada';
  end if;

  if v_invite.expires_at < now() then
    raise exception 'Invitacion vencida';
  end if;

  if lower(v_invite.email) <> lower(v_user_email) then
    raise exception 'Esta invitacion pertenece a otro correo';
  end if;

  insert into public.empresa_usuarios (
    empresa_id,
    user_id,
    email,
    rol
  )
  values (
    v_invite.empresa_id,
    auth.uid(),
    lower(v_user_email),
    v_invite.rol
  )
  on conflict (empresa_id, user_id)
  do update set
    email = excluded.email,
    rol = excluded.rol;

  update public.invitaciones_empresa
    set estado = 'ACEPTADA',
        accepted_by = auth.uid()
  where id = v_invite.id;

  return query select v_invite.empresa_id, v_invite.rol;
end;
$$;

grant execute on function public.crear_invitacion_empresa(
  bigint,
  text,
  text
) to authenticated;

grant execute on function public.aceptar_invitacion_empresa(
  text
) to authenticated;

grant usage on schema public to authenticated;
grant select, insert, update, delete on all tables in schema public to authenticated;
grant usage, select on all sequences in schema public to authenticated;
